
export const GET_LABOURS= 'GET_LABOURS_LIST'
export const GET_LABOURS_SUCCESS = 'GET_LABOURS_LIST_SUCCESS'
export const GET_LABOURDETAILS= 'GET_LABOURS_DETAILS'
export const GET_LABOURDETAILS_SUCCESS = 'GET_LABOUR_DETAILS_SUCCESS'
export const SEARCH_LABOUR = 'SEARCH_LABOUR'
export const SEARCH_LABOUR_SUCCESS = 'SEARCH_LABOUR_SUCCESS'
export const GET_LABOUR_ERROR = 'GET_LABOUR_ERROR'